export const searchAllServicedata = {
  itemTurnFilters: [
    {
      BackgroudColor: "backgroundwhite.png",
      FontColor: "#505050",
      PriceColor: "#00bed6",
      TabName: "1",
      StyleBackgroundPrice: 1,
      BoderColor: "#505050",
      ItemID: 72452,
      CategoryID: 0,
      CategoryName: "BODY MASSAGES",
      ItemCode: "",
      ItemName: "123",
      BasePrice: 123.0,
      Duration: 30,
      CustomerPrice: false,
      ItemColumns: null,
      IsCombo: null,
      IsPlus: false,
    },
    {
      BackgroudColor: "backgroundwhite.png",
      FontColor: "#505050",
      PriceColor: "#00bed6",
      TabName: "A",
      StyleBackgroundPrice: 1,
      BoderColor: "#505050",
      ItemID: 72451,
      CategoryID: 0,
      CategoryName: "BODY MASSAGES",
      ItemCode: "",
      ItemName: "a12",
      BasePrice: 123.0,
      Duration: 30,
      CustomerPrice: false,
      ItemColumns: null,
      IsCombo: null,
      IsPlus: false,
    },
    {
      BackgroudColor: "m-bg7.png",
      FontColor: "#505050",
      PriceColor: "#00BED6",
      TabName: "C",
      StyleBackgroundPrice: 2,
      BoderColor: "#FFCD00",
      ItemID: 30398,
      CategoryID: 0,
      CategoryName: "PEDICURE",
      ItemCode: "",
      ItemName: "Classic Pedi",
      BasePrice: 0.0,
      Duration: 25,
      CustomerPrice: true,
      ItemColumns: null,
      IsCombo: null,
      IsPlus: false,
    },
    {
      BackgroudColor: "bgmenu9.png",
      FontColor: "#505050",
      PriceColor: "#ffcd00",
      TabName: "E",
      StyleBackgroundPrice: null,
      BoderColor: "#505050",
      ItemID: 3749,
      CategoryID: 0,
      CategoryName: "FACIALS",
      ItemCode: "",
      ItemName: "Essential Facial",
      BasePrice: 40.0,
      Duration: 15,
      CustomerPrice: false,
      ItemColumns: null,
      IsCombo: false,
      IsPlus: false,
    },
    {
      BackgroudColor: "bgmenu11.png",
      FontColor: "#ffffff",
      PriceColor: "#f7941c",
      TabName: "E",
      StyleBackgroundPrice: null,
      BoderColor: "#505050",
      ItemID: 3752,
      CategoryID: 0,
      CategoryName: "MORE",
      ItemCode: "",
      ItemName: "EXTRA",
      BasePrice: 0.0,
      Duration: 0,
      CustomerPrice: true,
      ItemColumns: null,
      IsCombo: false,
      IsPlus: false,
    },
    {
      BackgroudColor: "White",
      FontColor: "#505050",
      PriceColor: "#00bed6",
      TabName: "E",
      StyleBackgroundPrice: null,
      BoderColor: "#505050",
      ItemID: 45887,
      CategoryID: 0,
      CategoryName: "EYELASHES",
      ItemCode: "",
      ItemName: "eye asian",
      BasePrice: 90.0,
      Duration: 90,
      CustomerPrice: false,
      ItemColumns: null,
      IsCombo: null,
      IsPlus: false,
    },
    {
      BackgroudColor: "White",
      FontColor: "#505050",
      PriceColor: "#00bed6",
      TabName: "E",
      StyleBackgroundPrice: null,
      BoderColor: "#505050",
      ItemID: 63748,
      CategoryID: 0,
      CategoryName: "EYELASHES",
      ItemCode: "",
      ItemName: "Eye Service 1",
      BasePrice: 32.0,
      Duration: 20,
      CustomerPrice: false,
      ItemColumns: null,
      IsCombo: null,
      IsPlus: false,
    },
    {
      BackgroudColor: "White",
      FontColor: "#505050",
      PriceColor: "#00bed6",
      TabName: "E",
      StyleBackgroundPrice: null,
      BoderColor: "#505050",
      ItemID: 63749,
      CategoryID: 0,
      CategoryName: "EYELASHES",
      ItemCode: "",
      ItemName: "Eye Service 2",
      BasePrice: 15.0,
      Duration: 30,
      CustomerPrice: false,
      ItemColumns: null,
      IsCombo: null,
      IsPlus: false,
    },
    {
      BackgroudColor: "White",
      FontColor: "#505050",
      PriceColor: "#00bed6",
      TabName: "E",
      StyleBackgroundPrice: null,
      BoderColor: "#505050",
      ItemID: 63750,
      CategoryID: 0,
      CategoryName: "EYELASHES",
      ItemCode: "",
      ItemName: "Eye Service 3",
      BasePrice: 23.0,
      Duration: 35,
      CustomerPrice: false,
      ItemColumns: null,
      IsCombo: null,
      IsPlus: false,
    },
    {
      BackgroudColor: "bgmenu3.png",
      FontColor: "#ffffff",
      PriceColor: "#ffcd00",
      TabName: "F",
      StyleBackgroundPrice: null,
      BoderColor: "#505050",
      ItemID: 53884,
      CategoryID: 0,
      CategoryName: "BODY MASSAGES",
      ItemCode: "",
      ItemName: "ffff",
      BasePrice: 4.0,
      Duration: 4,
      CustomerPrice: false,
      ItemColumns: null,
      IsCombo: null,
      IsPlus: true,
    },
    {
      BackgroudColor: "White",
      FontColor: "#505050",
      PriceColor: "#00bed6",
      TabName: "G",
      StyleBackgroundPrice: null,
      BoderColor: "#505050",
      ItemID: 48976,
      CategoryID: 0,
      CategoryName: "SHELLAC MANICURES",
      ItemCode: "",
      ItemName: "Gel",
      BasePrice: 39.99,
      Duration: 25,
      CustomerPrice: false,
      ItemColumns: null,
      IsCombo: null,
      IsPlus: true,
    },
    {
      BackgroudColor: "m-bg7.png",
      FontColor: "#505050",
      PriceColor: "#00BED6",
      TabName: "G",
      StyleBackgroundPrice: 2,
      BoderColor: "#FFCD00",
      ItemID: 30397,
      CategoryID: 0,
      CategoryName: "PEDICURE",
      ItemCode: "",
      ItemName: "Gel Pedicure",
      BasePrice: 20.0,
      Duration: 30,
      CustomerPrice: false,
      ItemColumns: null,
      IsCombo: null,
      IsPlus: false,
    },
    {
      BackgroudColor: "m-bg6.png",
      FontColor: "#505050",
      PriceColor: "#00BED6",
      TabName: "G",
      StyleBackgroundPrice: 2,
      BoderColor: "#8B85CA",
      ItemID: 30399,
      CategoryID: 0,
      CategoryName: "MULTIPLE SERVICES",
      ItemCode: "",
      ItemName: "Gel Polish Feet",
      BasePrice: 45.0,
      Duration: 50,
      CustomerPrice: false,
      ItemColumns: null,
      IsCombo: null,
      IsPlus: false,
    },
    {
      BackgroudColor: "m-bg6.png",
      FontColor: "#505050",
      PriceColor: "#00BED6",
      TabName: "G",
      StyleBackgroundPrice: 2,
      BoderColor: "#8B85CA",
      ItemID: 30400,
      CategoryID: 0,
      CategoryName: "MULTIPLE SERVICES",
      ItemCode: "",
      ItemName: "Gel Polish Hands",
      BasePrice: 50.0,
      Duration: 60,
      CustomerPrice: false,
      ItemColumns: null,
      IsCombo: null,
      IsPlus: false,
    },
    {
      BackgroudColor: "bgmenu7.png",
      FontColor: "#505050",
      PriceColor: "#00bed6",
      TabName: "M",
      StyleBackgroundPrice: null,
      BoderColor: "#505050",
      ItemID: 30152,
      CategoryID: 0,
      CategoryName: "BODY MASSAGES",
      ItemCode: "",
      ItemName: "Massage Body",
      BasePrice: 30.0,
      Duration: 45,
      CustomerPrice: false,
      ItemColumns: null,
      IsCombo: null,
      IsPlus: false,
    },
    {
      BackgroudColor: "m-bg6.png",
      FontColor: "#505050",
      PriceColor: "#00BED6",
      TabName: "M",
      StyleBackgroundPrice: 2,
      BoderColor: "#8B85CA",
      ItemID: 63745,
      CategoryID: 0,
      CategoryName: "MULTIPLE SERVICES",
      ItemCode: "",
      ItemName: "Multiple Service 1",
      BasePrice: 34.0,
      Duration: 60,
      CustomerPrice: false,
      ItemColumns: null,
      IsCombo: null,
      IsPlus: false,
    },
    {
      BackgroudColor: "m-bg6.png",
      FontColor: "#505050",
      PriceColor: "#00BED6",
      TabName: "M",
      StyleBackgroundPrice: 2,
      BoderColor: "#8B85CA",
      ItemID: 63746,
      CategoryID: 0,
      CategoryName: "MULTIPLE SERVICES",
      ItemCode: "",
      ItemName: "Multiple Service 2",
      BasePrice: 0.0,
      Duration: 55,
      CustomerPrice: true,
      ItemColumns: null,
      IsCombo: null,
      IsPlus: false,
    },
    {
      BackgroudColor: "m-bg6.png",
      FontColor: "#505050",
      PriceColor: "#00BED6",
      TabName: "M",
      StyleBackgroundPrice: 2,
      BoderColor: "#8B85CA",
      ItemID: 63747,
      CategoryID: 0,
      CategoryName: "MULTIPLE SERVICES",
      ItemCode: "",
      ItemName: "Multiple Service 3",
      BasePrice: 53.0,
      Duration: 60,
      CustomerPrice: false,
      ItemColumns: null,
      IsCombo: null,
      IsPlus: false,
    },
    {
      BackgroudColor: "bgmenu3.png",
      FontColor: "#ffffff",
      PriceColor: "#ffcd00",
      TabName: "S",
      StyleBackgroundPrice: null,
      BoderColor: "#505050",
      ItemID: 34902,
      CategoryID: 0,
      CategoryName: "BODY MASSAGES",
      ItemCode: "",
      ItemName: "Servia sad wqe fasd asedqweasdasd áđá",
      BasePrice: 5.0,
      Duration: 5,
      CustomerPrice: false,
      ItemColumns: null,
      IsCombo: null,
      IsPlus: false,
    },
    {
      BackgroudColor: "m-bg7.png",
      FontColor: "#505050",
      PriceColor: "#00BED6",
      TabName: "S",
      StyleBackgroundPrice: 2,
      BoderColor: "#FFCD00",
      ItemID: 63738,
      CategoryID: 0,
      CategoryName: "PEDICURE",
      ItemCode: "",
      ItemName: "service 1",
      BasePrice: 35.0,
      Duration: 35,
      CustomerPrice: false,
      ItemColumns: null,
      IsCombo: null,
      IsPlus: false,
    },
    {
      BackgroudColor: "m-bg7.png",
      FontColor: "#505050",
      PriceColor: "#00BED6",
      TabName: "S",
      StyleBackgroundPrice: 2,
      BoderColor: "#FFCD00",
      ItemID: 63739,
      CategoryID: 0,
      CategoryName: "PEDICURE",
      ItemCode: "",
      ItemName: "Servive 2",
      BasePrice: 19.0,
      Duration: 19,
      CustomerPrice: false,
      ItemColumns: null,
      IsCombo: null,
      IsPlus: false,
    },
    {
      BackgroudColor: "m-bg7.png",
      FontColor: "#505050",
      PriceColor: "#00BED6",
      TabName: "S",
      StyleBackgroundPrice: 2,
      BoderColor: "#FFCD00",
      ItemID: 63740,
      CategoryID: 0,
      CategoryName: "PEDICURE",
      ItemCode: "",
      ItemName: "Servive 3",
      BasePrice: 27.0,
      Duration: 27,
      CustomerPrice: false,
      ItemColumns: null,
      IsCombo: null,
      IsPlus: false,
    },
    {
      BackgroudColor: "m-bg7.png",
      FontColor: "#505050",
      PriceColor: "#00BED6",
      TabName: "S",
      StyleBackgroundPrice: 2,
      BoderColor: "#FFCD00",
      ItemID: 63741,
      CategoryID: 0,
      CategoryName: "PEDICURE",
      ItemCode: "",
      ItemName: "Servive 4",
      BasePrice: 38.0,
      Duration: 30,
      CustomerPrice: false,
      ItemColumns: null,
      IsCombo: null,
      IsPlus: false,
    },
    {
      BackgroudColor: "bgmenu3.png",
      FontColor: "#ffffff",
      PriceColor: "#ffcd00",
      TabName: "T",
      StyleBackgroundPrice: null,
      BoderColor: "#505050",
      ItemID: 72426,
      CategoryID: 0,
      CategoryName: "BODY MASSAGES",
      ItemCode: "",
      ItemName: "test deposit",
      BasePrice: 0.01,
      Duration: 0,
      CustomerPrice: false,
      ItemColumns: null,
      IsCombo: null,
      IsPlus: false,
    },
    {
      BackgroudColor: "backgroundwhite.png",
      FontColor: "#505050",
      PriceColor: "#00bed6",
      TabName: "T",
      StyleBackgroundPrice: 1,
      BoderColor: "#505050",
      ItemID: 44703,
      CategoryID: 0,
      CategoryName: "PEDICURE",
      ItemCode: "",
      ItemName: "tét",
      BasePrice: 0.0,
      Duration: 5,
      CustomerPrice: true,
      ItemColumns: null,
      IsCombo: null,
      IsPlus: false,
    },
  ],
};
export const SearchServicedata = {
  listColumn: [
    [
      {
        ColumnName: "",
        FontColor: "#ffffff",
        PriceColor: "#ffcd00",
        IndexColumn: null,
        BackgroudColor: "bgmenu3.png",
        StyleBackgroundPrice: null,
        BoderColor: "#505050",
        IsRetail: false,
        Description: "?",
        ItemID: 34902,
        CategoryID: 3,
        CategoryName: null,
        ItemCode: "",
        ItemName: "Servia sad wqe fasd asedqweasdasd áđá",
        BasePrice: 5,
        Duration: 5,
        CustomerPrice: false,
        ItemColumns: 1,
        IsCombo: null,
        IsPlus: false,
      },
      {
        ColumnName: "",
        FontColor: "#ffffff",
        PriceColor: "#ffcd00",
        IndexColumn: null,
        BackgroudColor: "bgmenu3.png",
        StyleBackgroundPrice: null,
        BoderColor: "#505050",
        IsRetail: false,
        Description: "",
        ItemID: 53884,
        CategoryID: 3,
        CategoryName: null,
        ItemCode: "",
        ItemName: "ffff",
        BasePrice: 4,
        Duration: 4,
        CustomerPrice: false,
        ItemColumns: 1,
        IsCombo: null,
        IsPlus: true,
      },
      {
        ColumnName: "",
        FontColor: "#ffffff",
        PriceColor: "#ffcd00",
        IndexColumn: null,
        BackgroudColor: "bgmenu3.png",
        StyleBackgroundPrice: null,
        BoderColor: "#505050",
        IsRetail: false,
        Description: "",
        ItemID: 72426,
        CategoryID: 3,
        CategoryName: null,
        ItemCode: "",
        ItemName: "test deposit",
        BasePrice: 0.01,
        Duration: 0,
        CustomerPrice: false,
        ItemColumns: 1,
        IsCombo: null,
        IsPlus: false,
      },
    ],
    [
      {
        ColumnName: "null",
        FontColor: "#505050",
        PriceColor: "#00bed6",
        IndexColumn: null,
        BackgroudColor: "bgmenu7.png",
        StyleBackgroundPrice: null,
        BoderColor: "#505050",
        IsRetail: false,
        Description: "",
        ItemID: 30152,
        CategoryID: 3,
        CategoryName: null,
        ItemCode: "",
        ItemName: "Massage Body",
        BasePrice: 30,
        Duration: 45,
        CustomerPrice: false,
        ItemColumns: 2,
        IsCombo: null,
        IsPlus: false,
      },
    ],
    [
      {
        ColumnName: "Cột 3",
        FontColor: "#505050",
        PriceColor: "#00bed6",
        IndexColumn: null,
        BackgroudColor: "backgroundwhite.png",
        StyleBackgroundPrice: 1,
        BoderColor: "#505050",
        IsRetail: false,
        Description: "",
        ItemID: 72451,
        CategoryID: 3,
        CategoryName: null,
        ItemCode: "",
        ItemName: "a12",
        BasePrice: 123,
        Duration: 30,
        CustomerPrice: false,
        ItemColumns: 3,
        IsCombo: null,
        IsPlus: false,
      },
      {
        ColumnName: "Cột 3",
        FontColor: "#505050",
        PriceColor: "#00bed6",
        IndexColumn: null,
        BackgroudColor: "backgroundwhite.png",
        StyleBackgroundPrice: 1,
        BoderColor: "#505050",
        IsRetail: false,
        Description: "",
        ItemID: 72452,
        CategoryID: 3,
        CategoryName: null,
        ItemCode: "",
        ItemName: "123",
        BasePrice: 123,
        Duration: 30,
        CustomerPrice: false,
        ItemColumns: 3,
        IsCombo: null,
        IsPlus: false,
      },
    ],
  ],
};
