export const InfoClient = {
  Address: null,
  AtRisk: null,
  Birthday: null,
  City: null,
  ContactPhone: "Client No Phone",
  Country: null,
  Coupon: "",
  CustomerCode: null,
  CustomerID: 724691,
  CustomerName: "\nVU Trinh\n GUEST 1 G3 G2 G7",
  CustomerType: "Reward",
  Email: "",
  FavouritePolish: null,
  FavouriteTech: "",
  FavouriteTechs1: "",
  FavouriteTechs2: "",
  FavouriteTechs3: "",
  FirstName: "\nVU Trinh\n GUEST 1 G3 G2 ",
  FristVist: null,
  ImageFileName: null,
  IsBlackList: false,
  IsChangePhone: true,
  IsChangePhoneWhenReward: null,
  IsChild: true,
  IsClientVerify: null,
  IsDeleted: null,
  IsKid: null,
  IsVerifyPhoneWithMango: null,
  IsVip: null,
  JoinDate: null,
  LastName: "G7",
  LastVist: null,
  MemberID: null,
  MemberStatus: "RewardsPoint",
  Notes: null,
  NotesApp: null,
  PasswordLoginWeb: null,
  RCPCustomer: null,
  Rating: 0,
  RatingDate: null,
  RewardsMember: null,
  RewardsPoint: 0,
  State: null,
  Title: null,
  TotalAmount: null,
  TotalSpentByYear: 0,
  Verification: null,
  VisitCount: null,
  VisitCountByYear: null,
  WorkPhone: null,
  Zip: null,
};
